package hexlet.code;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

import java.sql.SQLException;

public class DatabaseInitializer {
    private static HikariDataSource dataSource;

    public static HikariDataSource getDataSource() {
        return dataSource;
    }

    public static void initialize() throws SQLException {
        String jdbcUrl = System.getenv().getOrDefault("JDBC_DATABASE_URL", "jdbc:h2:mem:project;DB_CLOSE_DELAY=-1");
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(jdbcUrl);
        if (jdbcUrl.contains("postgresql")) {
            config.setUsername("postgres");
            config.setPassword("postgres");
        }
        dataSource = new HikariDataSource(config);

        String sql = """
                CREATE TABLE IF NOT EXISTS urls (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL
                );
                CREATE TABLE IF NOT EXISTS url_checks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    url_id BIGINT REFERENCES urls(id),
                    status_code INTEGER,
                    title VARCHAR(255),
                    h1 VARCHAR(255),
                    description TEXT,
                    created_at TIMESTAMP NOT NULL
                );
                """;

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    public static void close() {
        if (dataSource != null) {
            dataSource.close();
        }
    }
}
