package hexlet.code;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseInitializer {
    public static void initialize() throws SQLException {
        try (Connection conn = Database.getDataSource().getConnection();
             Statement stmt = conn.createStatement()) {
            String sql = """
                CREATE TABLE IF NOT EXISTS urls (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL UNIQUE,
                    created_at TIMESTAMP NOT NULL
                );
                CREATE TABLE IF NOT EXISTS url_checks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    url_id BIGINT NOT NULL,
                    status_code INT,
                    title TEXT,
                    h1 TEXT,
                    description TEXT,
                    created_at TIMESTAMP NOT NULL,
                    FOREIGN KEY (url_id) REFERENCES urls(id)
                );
            """;
            stmt.execute(sql);
        }
    }
}
